# Generated by Django 4.1.3 on 2022-11-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCompras',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('valor_total', models.FloatField()),
                ('data_compra', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floriculturaapp.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoHistoricoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('idHistoricoCompras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_historico', to='floriculturaapp.historicocompras')),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_historico', to='floriculturaapp.produto')),
            ],
        ),
        migrations.AddField(
            model_name='historicocompras',
            name='compras',
            field=models.ManyToManyField(related_name='historico', through='floriculturaapp.ProdutoHistoricoCompras', to='floriculturaapp.produto'),
        ),
    ]
