# Generated by Django 4.1.3 on 2022-11-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floriculturaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_produto', to='floriculturaapp.produto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_usuario', to='floriculturaapp.usuario')),
            ],
        ),
    ]
